Går bort fra tps i ArbeidsfordelingService.finnBehandlendeEnhetForPerson
navikt/familie-integrasjoner pull request #610
Opened 2022-04-25 12:04 UTC by tnarland

og tar i bruk pdl

2022-04-25 12:13 UTC, blommish approved these changes

2022-04-26 10:34 UTC, charliemidtlyng commented on src/main/java/no/nav/familie/integrasjoner/arbeidsfordeling/ArbeidsfordelingService.kt
> +        val personinfo = personopplysningerService.hentPersoninfo(personIdent, tema, PersonInfoQuery.ENKEL)
Dette temaet er IKKE det samme som temaet vi sender inn i funksjonen

2022-04-26 10:35 UTC, charliemidtlyng requested changes
Denne endringen vil brekke for alle oppslag for enheter som IKKE er ENF/BAR/KON:

Eksempel: 
Når vi skal finne enhet for oppfølgingsoppgave så sender vi inn tema `OPP`, men da vil kallet mot PDL tryne fordi vi ikke har tilgang til å hente ut personopplysninger for tema `OPP` - dette temaet må være enten `ENF` eller `BAR` - litt usikker på om det har noe å si hva vi setter inn der, egentlig..?

2022-04-26 11:57 UTC, charliemidtlyng commented
Forslag til forbedring her: https://github.com/navikt/familie-integrasjoner/pull/617

Vi skal teste det i EF nå

2022-04-26 12:15 UTC, charliemidtlyng approved these changes
Merget inn løsning for EF sin del

2022-04-26 12:47 UTC, merged